version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/BlueberryMartApp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/BlueberryMart.Api"
    schedule:
      interval: "weekly"
