namespace BlueberryMart.Api.Models.Responses;

/// <summary>
/// The set of fields a shareholder can pick from when building a chart. Generated by
/// introspecting the <c>sales_fact</c> table schema (broad + auto-growing), with a
/// thin semantic layer for friendly labels, allowed aggregations, and a few synthetic
/// measures (order/line/customer counts).
/// </summary>
public record AnalyticsCatalog(
    bool Enabled,
    IReadOnlyList<CatalogDimension> Dimensions,
    IReadOnlyList<CatalogMeasure> Measures);

/// <summary>A groupable / filterable field.</summary>
public record CatalogDimension(string Id, string Label, string DataType);

/// <summary>An aggregatable field and the aggregations allowed on it.</summary>
public record CatalogMeasure(string Id, string Label, IReadOnlyList<string> Aggs);

/// <summary>Result of running a query: column metadata + the rows.</summary>
public record AnalyticsResult(
    IReadOnlyList<AnalyticsColumn> Columns,
    IReadOnlyList<IReadOnlyDictionary<string, object?>> Rows);

/// <summary>One output column, keyed by its result alias.</summary>
public record AnalyticsColumn(string Key, string Label, string Role);
